### ISSUE TITLE
Stock status for source not transfers during mass action 'Transfer Inventory To Source' on Products grid

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1509]
### Preconditions

1. Magento MSI
2. Several products created assigned to default source with qty on source = 100 and stock status = 'Out of stock'
3. Create additional 'Test source 1'
4. Create additional 'Test stock 1' and assign 'Test source 1' to it 

### Steps to reproduce

1. Login to admin
2. Go to "Catalog" -> "Products"
3. Select uor created products in Products grid
4. Select in 'Action' drop-down menu 'Transfer Inventory To Source'
5. Select on 'Bulk Inventory Transfer' page' : Transfer from source 'Default source' to source 'Test Source 1' and click button "Inventory Transfer'

### Expected result

1. Your products should get assigned to  'Test source 1' with qty on source = 100 and stock status = 'Out of stock'

### Actual result

1. Products got assigned to  'Test source 1' with qty on source = 100 and stock status = 'In stock'

**Comment by phoenix128** [comment]
@smoskaluk , there was a control in place for stock status depending on the final quantity, because we should also consider another scenario:

- Your precondition on `Default Stock`.
- Quantity already existing in `Test source 1` and `In stock` condition.

In this condition we should keep `In stock` while transferring from `Default Source` to `Test source 1`.

We could check if the source item was previsously assigned to destination source or not and change the behaviour accordingly. Do you agree with this?

**Comment by smoskaluk** [comment]
Hi @phoenix128!  I think your considerations are quite reasonable, but from other hand, merchant might be willing to transfer total configuration from one warehouse to another, so all previous settings for source should overwritten. I will redirect your comment to Mark Brinton and we'll see what is better to do.

**Comment by smoskaluk** [comment]
Hi @phoenix128! Mark Brinton consider that 'Transfer Inventory To Source' should persist settings (such as notify quantity etc) from the source the transfer is made FROM. In other words, it will overwrite settings on the destination source. 
Best regards!

**Comment by ivy00johns** [comment]
*Skipped Tests:*
1. `<testCaseId value="1520"/>`
2. `<testCaseId value="1518"/>`
3. `<testCaseId value="1523"/>`
4. `<testCaseId value="1522"/>`

**Comment by phoenix128** [comment]
Fixed in https://github.com/magento-engcom/msi/pull/1648 .
