### ISSUE TITLE
Low stock report not displays products on Single stock mode

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1543]
### Preconditions

1. Magento with MSI in Single stock mode
2. Simple or virtual product created with Qty = 10

### Steps to reproduce

1. Set in Configuration - Catalog - Inventory - Notify for Quantity Below = 20
2. Open Reports - Low Stock

### Expected result

1. Products should be displayed in report

### Actual result

1. Products are not displayed in report

**Comment by aleron75** [comment]
I investigated a bit and I think the issue generates because `\Magento\InventoryLowQuantityNotification\Model\ResourceModel\LowQuantityCollection::joinInventoryConfiguration()` method joins the `inventory_low_stock_notification_configuration` table and if SKUs are not in that table, the join returns empty result.

I don't understand who is responsible for inserting records in the `inventory_low_stock_notification_configuration` table, other than the migration setup script defined in `\Magento\InventoryLowQuantityNotification\Setup\Patch\Data\MigrateCatalogInventoryNotifyStockQuantityData`.

Without matching records in that table, the join will always return an empty set.

Maybe @naydav can help me understand better.

**Comment by aleron75** [comment]
Probably I discovered something more: in the `\Magento\InventoryLowQuantityNotificationAdminUi\Observer\ProcessSourceItemConfigurationsObserver::execute()` at line 62 the `$sources` array is empty. 

Being `$sources` empty, the `inventory_low_stock_notification_configuration` table is not populated.

What I don't get now is:
1. why the `$sources` array is empty
1. in case I don't change configuration in product but in "Configuration - Catalog - Inventory - Notify for Quantity Below", shouldn't a similar kind of observer be defined to update the `inventory_low_stock_notification_configuration` for each eligible product? I didn't find it but maybe it's me missing something.

**Comment by aleron75** [comment]
Ok, regarding point (1) _"why the `$sources` array is empty"_ I think that I can solve by checking if we are in single source mode; still in doubt regarding point (2)

**Comment by aleron75** [comment]
Regarding point (2) I verified that if I save config, the `inventory_low_stock_notification_configuration` table is updated but not with all products, only with those already in the table.

**Comment by aleron75** [comment]
Another issue is that mass update of stock items doesn't populate `inventory_low_stock_notification_configuration` table; still to check what happens with import
