### ISSUE TITLE
"Only X left Treshhold' for products in combination with negative 'Out-of-Stock Threshold' and backorders doesn't work

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1694]
### Preconditions
1. Magento with MSI on single stock mode

### Steps to reproduce
1. Navigate to admin area.
2. Create simple or virtual product with qty = 10
3. In 'Advanced inventory' set for Backorders = Allow qty below 0 and for 'Out-of-Stock Threshold' = -10 (negative value)
4. Navigate to Stores > Configuration > Catalog > Inventory > Stock Options
5. Set 'Only X left Threshold' = 10.
6. Run full reindex and flush cache
7. Open product page on frontend.

### Expected result
1. "Only 10 left" message appears on product view page.

### Actual result
1. "Only 10 left" message doesn't appear on product view page.

PS Same behaviour for multy source mode

**Comment by larsroettig** [comment]
Thank you for the report @smoskaluk.

I can reproduce this Issue on the latest development version of MSI.

**Comment by larsroettig** [comment]
Hi @smoskaluk,
I checked and debugged it works well but your expectation is wrong. 

Because you configure with*-10* you have *20* saleable products left this why it is nor show on
the product page. 

It works well with 

Navigate to Stores > Configuration > Catalog > Inventory > Stock Options
Set 'Only X left Threshold' = 20 or **qty = 0**

**Comment by smoskaluk** [comment]
Hi @larsroettig , thank you, now I see..)
