### ISSUE TITLE
Grouped(or configurable) product remains on category page after all quantity has been sold.

### ISSUE THREAD

**Issue by nmalevanec** [magento/inventory#1695]
### Preconditions
1. Magento with MSI.
2. Additional stock with additional assigned source created.
3. Main website assigned to additional stock as sales channel.

### Steps to reproduce
1. Login to admin area.
2. Create simple product and assign it to additional source with qty = 100.
3. Create virtual product and assign it to additional source with qty = 100.
4. Create grouped product assign to category and add both simple and virtual to group with default qty = 100.
5. Navigate to storefront category page.
6. Add grouped product to cart and place order.
7. Navigate to admin area Sales > Orders.
8. Open created order and create full shipment and full invoice.
9. Navigate to storefront category page.

### Expected result
1. Grouped product is absent on category page as all it's qty has been sold.

### Actual result
1. Grouped product remains on category page.

### Additional info
On PDP grouped product has status "Out of Stock'. After manually flushing cache product disappears from category page. 

The same situation with configurable product. When all it's qty by all child's has been sold expected that the configurable product remains on category page.

**Comment by IvanPletnyov** [comment]
@maghamed Grouped (or configurable) product remains on category page after all quantity has been sold because when we flush cache in plugin `\Magento\InventoryCache\Plugin\InventoryIndexer\Indexer\Source\SourceItemIndexer\CacheFlush::afterExecuteList` we get product ids by source item ids from service `\Magento\InventoryIndexer\Model\ResourceModel\GetProductIdsBySourceItemIds::execute` , but it service return only children products ids and not return parent product ids (grouped id or configurable id). 

For fix we need create service which get children products ids by logic the same as `\Magento\InventoryIndexer\Model\ResourceModel\GetProductIdsBySourceItemIds::execute` and get parent product ids by logic the same as `\Magento\CatalogInventory\Model\Indexer\Stock\AbstractAction::getRelationsByChild`, but for build select for get parent ids in module InventoryCache we need add new dependency to module catalog, in order to get link field.
