### ISSUE TITLE
Slow array function used in loop

### ISSUE THREAD

**Issue by larsroettig** [magento/inventory#1873]
Let's start with an example demonstrating the case:
```php
    $options = [];
    foreach ($configurationSources as $source) {
        /* something happens here */
        $options = array_merge($options, $source->getOptions());
    }
```

In order to reduce execution time we can modify the code and perform the merge operation only once:
```php
    /* the inner empty array covers cases when no loops were made */
    $options = [[]];
    foreach ($configurationSources as $source) {
        /* something happens here */
        $options[] = $source->getOptions(); // <- yes, we'll use a little bit more memory
    }
    /* PHP below 5.6 */
    $options = call_user_func_array('array_merge', $options);

    /* PHP 5.6+: more friendly to refactoring as less magic involved */
    $options = array_merge(...$options);
```

Currently in

**Comment by maghamed** [comment]
@larsroettig  please update your PR and re-run builds

**Comment by sidolov** [comment]
Hi @larsroettig , thank you for your investigation and suggestion on how to make micro performance optimizations! Looks like you have commits related to the described issue, please, open pull request if you are ready to contribute it!  I believe we can close the issue since it's don't have a high impact on the product. Thank you for your collaboration!
