### ISSUE TITLE
No returns to the source for configurable product during credit memo after partial invoice and shipping created

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1905]
### Preconditions

1. Magento MSI multy stock mode
2. Configurable product created with 2 dropdown color options "Red" and "Black" having weight and qty on default source = 100

### Steps to reproduce

1. Place order with 10 items of configurable 'Red" 
(Qty on source = 100, salable qty = 90)
2. Create partial invoice for 3 items
3. Create partial shipment for 3 items
(Qty on source = 97, salable qty = 90)
4. Create credit memo with return to stock for 3 items
5. Cancel order
6. Check in DB reservations in table "inventory_reservation"

### Expected result

1. Qty on default source of configurable 'Red" should be 100 

### Actual result

1. Qty on default source of configurable 'Red" = 97  (No returns to source)
2. Salable qty  of configurable 'Red" = 100

![image](https://user-images.githubusercontent.com/27818516/48541996-ad180000-e8c6-11e8-80cf-3d2b200f81e9.png)

**Comment by vickdoan** [comment]
I think the wrong qty was caused by $processedQty in the aroundExecute function ( see file app/code/Magento/InventorySales/Plugin/SalesInventory/ProcessReturnQtyOnCreditMemoPlugin.php)

I tried to invoice 3 qtys for Red option but  the "qty_invoiced" is different between the parent item and the child item in the "sales_order_item" table.

![image](https://user-images.githubusercontent.com/15009867/48758710-906b3600-ecd3-11e8-8550-ed50b3e244c0.png)


$processedQty = $orderItem->getQtyInvoiced() - $orderItem->getQtyRefunded() + $qty;

The  getQtyInvoiced should be 3 instead of 10 for Red option and it's the reason which caused the wrong qty for the Red child product.
