### ISSUE TITLE
Performance degradation on catalog page

### ISSUE THREAD

**Issue by IvanPletnyov** [magento/inventory#1921]
### Preconditions
1. Magento with MSI
2. Load performance fixtures
`bin/magento setup:perf:generate-fixtures setup/performance-toolkit/profiles/ce/small.xml`
3. [Enable SQL profiler](https://devdocs.magento.com/guides/v2.1/config-guide/db-profiler/db-profiler.html)

### Steps to reproduce
1. Open category page (example http://localhost/category-4.html)

### Magento with MSI profiler results
SQL query example:
![msi](https://user-images.githubusercontent.com/26973706/48910702-5045b800-ee79-11e8-99ee-a9fed7d04dd0.png)

![image](https://user-images.githubusercontent.com/26973706/48932158-06091900-ef03-11e8-9cb3-e011f56e3e20.png)

### Magento without MSI profiler results
SQL query example:
![ce](https://user-images.githubusercontent.com/26973706/48910731-62275b00-ee79-11e8-8a17-97abae9ca1de.png)

![image](https://user-images.githubusercontent.com/26973706/48932185-2b962280-ef03-11e8-9a54-478e30506c41.png)

### Query with explain
With MSI: 
1) With conditions 
![1](https://user-images.githubusercontent.com/26973706/48941306-aff89d80-ef23-11e8-9710-e908d51128f9.png)
2) Without conditions 
![2](https://user-images.githubusercontent.com/26973706/48941311-b9820580-ef23-11e8-94bb-e6f663a20022.png)

Without MSI:
![3](https://user-images.githubusercontent.com/26973706/48941315-c0a91380-ef23-11e8-9c8a-9c23ae118b12.png)

### Additional info
1. [Build on bamboo](https://bamboo.corp.magento.com/browse/MCCE23-PAT1710-CAT2-1) 
2. Paying attention, if we transfer all products from default stock  to custom stock, page load speed approximately equal to magento without MSI.
SQL load speed on custom stock:
![image](https://user-images.githubusercontent.com/26973706/48910923-eed21900-ee79-11e8-9e02-c06d795d1282.png)

**Comment by maghamed** [comment]
hey, @vickdoan  is there any update on this issue or maybe some assistance needed from our side?

**Comment by Stepa4man** [comment]
@maghamed, I did some investigation for category page performance.
I found 15 queries that have a very low performance. I have checked it 
And I have several conclusions:

- All slow queries contain join to inventory_stock_1 sql view and it can't be indexed because it's just view (query without this sql view works like 10 times faster)
- Some of the queries have unnecessary joins to catalog_product_enity table just for the purpose to provide sku for join inventory_stock_1. (We don't need it, once we have product_id field in inventory_stock_1. We have to get rid of this join in spite of this will not solve any performance issue)
- Join by sku field between inventory_stock_1 view and another table (join by varchar field is anyway slower then join by int, so using product_id from the previous paragraph will solve this issue)

I suppose that changing all joins `inventory_stock_1` view from sku to product_id will decrease at least 50% of all degradation.

Here is a db logging file with this 15 queries and stack trace.
(It was logged using medium profile)
[msi-performance.log](https://github.com/magento-engcom/msi/files/2684043/msi-performance.log)

P.S. I have already fixed with  [this pulll request](https://github.com/magento-engcom/msi/pull/1944) for category page
