### ISSUE TITLE
Can't use bulk API for inventory/source-items endpoint 

### ISSUE THREAD

**Issue by DnD-Mimosa** [magento/inventory#1961]
### Preconditions

1. Magento Commerce 2.3.0
2. Magento MSI

### Steps to reproduce

1. I'm trying to use the bulk API to update source items inventory through the endpoint inventory/source-items by using POST. As I saw in Magento documentation, if I want to use bulk API, I should call my endpoint like this :
https://magento.local/rest/async/bulk/V1/inventory/source-items
2. I tried with my own params and then with those one provided in the documentation :
`{"sourceItems":[{"sku":"new_product1","source_code":"default","quantity":1000,"status":1},{"sku":"new_product1","source_code":"default","quantity":2000,"status":1},{"sku":"new_product2","source_code":"default","quantity":500,"status":1},{"sku":"new_product2","source_code":"default","quantity":250,"status":1}]}`
(I just replaced source_code by the default one, present in my Magento)

### Expected result

1. Expected result was to have a 200 response
2. If I do not use bulk API endpoint, like this https://magento.local/rest/V1/inventory/source-items with the same params, I have a 200 response :
<img width="1140" alt="normal-api" src="https://user-images.githubusercontent.com/7805309/50442786-c4ec9600-0900-11e9-90f2-c00f2aa2dfd4.png">

### Actual result

1. I only have a 400 with following response :
`"message": "\"%fieldName\" is required. Enter and try again.",
    "parameters": {
        "fieldName": "sourceItems"
    }`
<img width="1139" alt="bulk-api" src="https://user-images.githubusercontent.com/7805309/50442789-cddd6780-0900-11e9-9326-8307615f04d6.png">

Does anyone have an idea ? 
Am I doing something wrong in my call on the bulk API ?

Thank you very much for your help !
NB : I think this issue is linked to this one #1036

**Comment by maghamed** [comment]
@DnD-Mimosa  thanks for this bug report! 
We will investigate it and get back with results shortly

**Comment by maghamed** [comment]
Hi @DnD-Mimosa, looks like you have an issue in the format of your REST request, and the root cause of the issue is that our API for Inventory SourceItem Save **is Bulk by its nature.**

As you can see, `SourceItemsSaveInterface` service accepts not a single SourceItem, but an array of SourceItems 
```php
namespace Magento\InventoryApi\Api;

/**
 * Service method for source items save multiple
 * Performance efficient API
 *
 * Used fully qualified namespaces in annotations for proper work of WebApi request parser
 *
 * @api
 */
interface SourceItemsSaveInterface
{
    /**
     * Save Multiple Source item data
     *
     * @param \Magento\InventoryApi\Api\Data\SourceItemInterface[] $sourceItems
     * @return void
     * @throws \Magento\Framework\Exception\InputException
     * @throws \Magento\Framework\Validation\ValidationException
     * @throws \Magento\Framework\Exception\CouldNotSaveException
     */
    public function execute(array $sourceItems): void;
}
```

This new design of Interfaces which work with array of entities is recommended in Magento Service Contract Design Guideline:
https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html#64-service-contracts-application-layer 
>6.4.3.2. Service contracts SHOULD support batch data processing. For example, an entity persisting method SHOULD accept an array of entities to persist instead of a single entity. Customizations implemented through plugins SHOULD be adjusted respectively.

It's different to what we had before with our Interfaces which have been already released before Magento 2.3.0, like Create Customer operation:

```php
/**
 * Interface for managing customers accounts.
 * @api
 * @since 100.0.2
 */
interface AccountManagementInterface
{
  //...
    /**
     * Create customer account. Perform necessary business operations like sending email.
     *
     * @param \Magento\Customer\Api\Data\CustomerInterface $customer
     * @param string $password
     * @param string $redirectUrl
     * @return \Magento\Customer\Api\Data\CustomerInterface
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function createAccount(
        \Magento\Customer\Api\Data\CustomerInterface $customer,
        $password = null,
        $redirectUrl = ''
    );
//...
}
```

which accepts only Single Customer as an input parameter

```xml
    <route url="/V1/customers" method="POST">
        <service class="Magento\Customer\Api\AccountManagementInterface" method="createAccount"/>
        <resources>
            <resource ref="anonymous"/>
        </resources>
    </route>
```

So that to increase efficency working with magento application in a headless way via REST communication Magento introduces `bulk` endpoints for REST communication:
https://devdocs.magento.com/guides/v2.3/rest/bulk-endpoints.html

The bulk combines multiple calls of the same type into an array and execute them as a single request.  So, no excessive HTTP round trip communication needed to process all entities of the same type.
https://devdocs.magento.com/guides/v2.3/rest/bulk-endpoints.html

`/async/bulk ` prefix is used to describe that Virtual Bulk endpoint should be used instead of Single Entity endpoint.

The payload of a bulk request contains an array of request bodies. For example, the minimal payload for creating four customers with POST /async/bulk/V1/customers would be structured as follows:
```json
[{
	"customer": {
		"email": "mshaw@example.com",
		"firstname": "Melanie Shaw",
		"lastname": "Doe"
	}
},
{
	"customer": {
		"email": "bmartin@example.com",
		"firstname": "Bryce",
		"lastname": "Martin"
	}
},
{
	"customer": {
		"email": "bmartin@example.com",
		"firstname": "Bryce",
		"lastname": "Martin"
	}
},
{
	"customer": {
		"email": "tgomez@example.com",
		"firstname": "Teresa",
		"lastname": "Gomez"
	}
}
]
```
 
as you see we wrap payload for one service into the array (entities of the same type, e.g. "customers" in this example).

But let's get back to SourceItem Save service, which is already Bulk api:
https://devdocs.magento.com/guides/v2.3/rest/modules/inventory/manage-source-items.html
`POST V1/inventory/source-items`
```json
{
  "sourceItems": [{
  	"sku": "new_product1",
         "source_code": "central",
         "quantity": 1000,
         "status": 1
  },
  {
  	"sku": "new_product1",
  	"source_code": "east",
  	"quantity": 2000,
  	"status": 1
  },
  {
  	"sku": "new_product2",
  	"source_code": "central",
  	"quantity": 500,
  	"status": 1
  },
  {
  	"sku": "new_product2",
  	"source_code": "east",
  	"quantity": 250,
  	"status": 1
  }]
}
```

If you do want to make this call as async you can apply `async` prefix righ before the endppoint
https://github.com/magento-engcom/bulk-api/wiki/Asynchronous-Web-API
`POST /async/V1/inventory/source-items`
this will make a call to be processed in asynchronious way. 
\* Don't forget to run Message Queue consumer to process the call
>Use the bin/magento queue:consumers:start async.operations.all command to enable asynchronous requests.
https://devdocs.magento.com/guides/v2.3/rest/asynchronous-web-endpoints.html

But if some wants to use Bulk endpoints functionality, which will wrap our SourceItem BULK call into another BULK (not sure that there is a business reason for doing this), the payload should represent and array of arrays.
So the payload you mentioned for `/async/bulk`  is not correct because you have just one array, but you need to wrap it with array on higher level like this:
```json
    [
        {
            "sourceItems":
            [
                {"sku":"new_product1","source_code":"default","quantity":1000,"status":1},
                {"sku":"new_product1","source_code":"default","quantity":2000,"status":1},
                {"sku":"new_product2","source_code":"default","quantity":500,"status":1},
                {"sku":"new_product2","source_code":"default","quantity":250,"status":1}
            ]
        },
        {
            "sourceItems":
            [
                {"sku":"new_product3","source_code":"default","quantity":1000,"status":1},
                {"sku":"new_product3","source_code":"default","quantity":2000,"status":1},
                {"sku":"new_product4","source_code":"default","quantity":500,"status":1},
                {"sku":"new_product4","source_code":"default","quantity":250,"status":1}
            ]
        }
    ]
```

**Comment by maghamed** [comment]
@DnD-Mimosa  if my answer above resolved your problem, could you please close this issue or leave a feedback so we can proceed further

**Comment by DnD-Mimosa** [comment]
Hi @maghamed, thank you very much for your answer and your time !

It works now 👍

**Comment by smoskaluk** [comment]
Hi @DnD-Mimosa!
Please change endpoint in your call like this <magento>rest/async/V1/inventory/source-items . 
Also if you have only one "default" source assigned to your products, params should be different as well
{"sourceItems":[{"sku":"new_product1","source_code":"default","quantity":1000,"status":1},{"sku":"new_product2","source_code":"default","quantity":500,"status":1}]}

**Comment by maghamed** [comment]
Great, thanks!
