### ISSUE TITLE
Source items deduction during checkout when order is successfully placed

### ISSUE THREAD

**Issue by jonathanribas** [magento/inventory#1968]
### Description
We are actually using a warehouse as our priority source and also an unified retail shops stock source. 
As MSI allows it, we would like to ship each order item line through the priority source that was chosen by SSA priority algorithm.

Order line items processed by our warehouse are processed every minute, if picking step is ok, our internal system asks automatically Magento 2 API for the shipment creation.
Order line items that will be deducted from our unified retail shops stock are processed by an external platform according to our retail shops managers decision, those orders could take some hours to be processed and then ask for the shipment creation through Magento 2 API automatically. 

Based on that, our internal system needs to know from which source the order line item will be shipped in advance in order to send it to the right place automatically. 

Let's imagine we have an SKU with saleable quantity equal to 2. It's availability is 1 in our warehouse source (priority) and the other one in our unified retail shops source. 
2 orders have been placed for this specific SKU between some seconds.
Our internal system application run and gets at the same time those 2 orders from M2 API, then we run an M2 SSA API call for each order to determine priority, it will tell us for the 2 orders that priority source is warehouse because at this point we haven't created shipment yet so Magento hasn't deducted quantity from physical source. We will then try to ship automatically those 2 orders from warehouse as it was selected by SSA but we only have a single piece in the warehouse, this is our actual problem. 

### Expected behavior
In order to have our expected behavior, as soon as we place an order from frontend or admin; stock, source selection and source item deduction should happen automatically based on our source priority during checkout or admin when order is placed successfully. We also need to flag each order line item to process our orders with the right source.
Source items deduction is not anymore handled on shipment creation.

### Benefits
This feature will benefit merchants that have automated workflows with multiple physical sources.

**Comment by sah-anshu** [comment]
### + Expected behavior
- If we can send a notification to Source Email, it will be helpful.

**Comment by maghamed** [comment]
Hi @jonathanribas , thanks for your feedback and feature request, we really appreciate that!
Now regarding your proposal. As for me what you need is not source deduction at the time of order placement, but Reservation mechanism on Source level (currently MSI provides Stock level reservations only). Source level reservations will allow to keep SSA result and prevent interfering of different orders between each other. 

The idea of Reservations on the Source level was initially proposed by @paales  https://github.com/magento-engcom/msi/issues/133
and as I know Paul has some implementation of such mechanism as well. 

Btw, we are experiencing similar issue in the scope of Store Pickup implementation either. Here is description of how we going to avoid it - https://github.com/magento-engcom/msi/wiki/Support-of-Store-Pickup-for-Multi-Source-Inventory#Race-condition-between-orders

In general the idea of Source reservations is closer to our desirable state than just deduction of Sources at the checkout time. Because doing so we can correctly track and represent exact processes happening in business, so we can predict when merchant needs to refill the stock on particular warehouse based on current load. 
Because when Order is placed - there is still time when product physically located on a warehouse and occupies the space even so it is already sold. Thus, if we would make source deduction immediately - we can't track the load of warehouse (track spare space), thus can't predict when need to order more products.
But we can achieve this with Source level reservations

**Comment by jonathanribas** [comment]
Hi @maghamed, thanks for your reply.

Source reservations by SSA for priority sounds good!

Have you already planned to include this feature in an MSI milestone?

**Comment by maghamed** [comment]
@jonathanribas I don't think that we will proceed on this story in the coming future (H1 of 2019, as we have quite a lot of other stories with higher priority to do) unless somebody would contribute it to MSI and we accept this contribution

**Comment by jonathanribas** [comment]
Hi @maghamed,

Ok, thank you.

**Comment by maghamed** [comment]
@jonathanribas you can watch the presentation of Source-Level reservations on recent MSI demo - https://www.youtube.com/watch?v=ggucjcaBHjI&feature=youtu.be&t=1260&app=desktop
