### ISSUE TITLE
Negative as well as decimal values are been accepted while assigning quantity against a source in the product creation form

### ISSUE THREAD

**Issue by ghoshsweta** [magento/inventory#1978]
### Preconditions (*)

1.Magento version 2.3.0
2.php version 7.2

### Steps to reproduce (*)

1)Login to Admin Panel
2)On left navigation goto Stores-> Inventory->sources
3)Create two source
4)Now goto left navigation Stores-> Inventory->stocks
5)Create stock with Sales Channels: the Main website, and add source created above to the stock
6)Go to Catalog->products
7)Click the edit button of any products which is a type of simple product 
8)fill in the required fields of the form
9)go to the sources option 
10)click on assign source
11)select a source and in the qty column enter a negative value or a decimal value. For example enter -15 or 2.3
12)save the product form
### Expected result (*)

1. Negative quantity should not be accepted while creating a product.
2. An appropriate error msg should be returned as soon as a user enters a negative value or a decimal value in the Qty field.

### Actual result (*)

1. The error message was not received when the user entered a negative value or a decimal value against the qty field
2. The product got created/saved successfully.
![screenshot_2019-01-10_18-13-31](https://user-images.githubusercontent.com/25763126/51015868-d33ee100-1593-11e9-9daa-1a3c3b4ad960.png)
![screenshot_2019-01-10_18-14-24](https://user-images.githubusercontent.com/25763126/51015869-d33ee100-1593-11e9-8d1f-66b68f1ef64d.png)

**Comment by maghamed** [comment]
Hi @swetacedcoss ,

thanks for the bug report.
Let's consider both of these possibilities: negative inventory amount and decimal value separately.

Negative inventory amount should be possible to enter and this possibility could be useful especially in case a Source represents Dropshipper. So, the inventory value represents not the actual Stock, but how many products Ordered and what's the "Inventory Debt" merchant has. Also, that could be useful, if the manufacture is involved and merchant just collects orders and them proceed with goods production.
Negative product amount was also possible in Magento before MSI, so that we don't introduce new behavior, but preserve an existing one.

 Regarding the possibility to use decimal values for product quantity we have a dedicated configuration setting.
You can modify global and product-specific inventory options through the following locations in the Magento Admin:

- Inventory page in the Stores > Configuration settings
- Sources section > Assigned Sources grid when editing a product in Catalog > Products
- Advanced Inventory page when editing a product 

`Qty Uses Decimals` - is a setting allowing decimal amounts, instead of whole numbers, for the quantity of a product. This is helpful for products sold by weight, volume, or length. Specified on the level of Source, calculated on the Stock level based on assigned Sources
https://github.com/magento-engcom/msi/wiki/Stock-and-Source-Configuration-design

**Comment by shikhamis11** [comment]
@maghamed in that case this issue must be closed
