### ISSUE TITLE
Stocks not visible on Stocks Page

### ISSUE THREAD

**Issue by richarddehoog** [magento/inventory#2045]
### Preconditions

1. I am using Magento 2.3
2. I have been able to add stocks, and i do see them in the product grids / salable QTY

### Steps to reproduce

1. When i add stock / assign sources i get the following result
2. https://prnt.sc/mlk2dt

### Expected result

1. Prviously i got a list with all stock
2.

### Actual result

1. https://prnt.sc/mlk2dt
2. In the product grid i do see that the stock is added https://prnt.sc/mlk24e

**Comment by IvanPletnyov** [comment]
Hey @richarddehoog  thanks for the issue report.

I could not reproduce this issue.
Tell me please, what version of MSI you installed ? Do you do composer installation or git?
Give me more information about steps. Is it fresh install or you upgraded from previous version ?

**Comment by richarddehoog** [comment]
Hello Ivan,

 

We have a fresh install, and then we have installed Aheadworks & Amasty extensions

 

We have already deactivated all extensions, but this did not solve the issue

 

We have installed the latest version of the MSI ( 1.1.0)

 

 

We have used composer for this

 

 

I can give you admin / SSH access if this helps

 

To make al long story short ( if this was not clear):

 

*	If we add stocks in stores => ad stock

*	The stock are not visible on the stocks page
*	I do see in the product grid that the added stock is added in column : salable QTY

 

My email is richard@growthefuture.eu <mailto:richard@growthefuture.eu>  if you want me to sent you credentials to login to admin / ssh

 

Richard

 

Van: IvanPletnyov <notifications@github.com> 
Verzonden: maandag 18 februari 2019 17:02
Aan: magento-engcom/msi <msi@noreply.github.com>
CC: richarddehoog <richard.de.hoog@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [magento-engcom/msi] Stocks not visible on Stocks Page (#2045)

 

Hey @richarddehoog <https://github.com/richarddehoog>  thanks for the issue report.

I've not reproduced yet this bug.
Tell me please, what version of MSI you are installing ? Do you do composer installation or git?
Give me more information about step. Is it fresh install or you update from previous version ?

**Comment by maghamed** [comment]
Hi @richarddehoog , thanks for your feedback. 

Could you please try to reproduce the bug with a fresh Magento 2.3 installation without 3rd party extensions, as even being deactivated they still could interfere with Magento. For example, if they changed something at the time when were installed. 

Currently, we did not manage to replicate this case, which is very basic from the Inventory management point of view, and we have a bunch of MFTF (acceptance) tests which test this behavior on a regular basis.


Ideally to try this use-case on Fresh Magento 2.3.0 + MSI 1.1.0 
then install the first extension and repeat the case, and after that install the last extension and see again the result.
So that we could see which extension cause a problem

**Comment by maghamed** [comment]
if the bug still exists, @richarddehoog  feel free to re-open the issue
