### ISSUE TITLE
Display out of stock product on category page

### ISSUE THREAD

**Issue by kandarp26** [magento/inventory#2112]
### Preconditions (*)

1. Magento 2.3.0 installed and MSI enabled
2.  Create new Source - testing_source

### Steps to reproduce (*)

1. Create product with 1 qty. 
2. Admin > catalog >stock option > Display Out of Stock Products = No 
3. Place order with same product
4. Navigate to the category list page 
--

### Expected result (*)

1. Product should disappear from the listing as it's out of stock 

### Actual result (*)

1. Product still remain on category list
2. When we go to the product page it show out of stock.

**Comment by smoskaluk** [comment]
Hi @kandarp26 ,  MSI works that way, that product will disappear not after placing order - but only after order completed (shipment created). You may notice in admin, on product grid that after placing order only salable qty on stock deducted for your product, but qty on source would be reduced only after shipping.

**Comment by jorgb90** [comment]
I don't think this is the preferred way? If there is 1  piece left it can't stay online until its shipped? When its bought and paid for it should be taken offline..

**Comment by kandarp26** [comment]
@smoskaluk  Magento have a setting Admin > catalog >stock option > Display Out of Stock Products = No. Where out of stock product is not display on frontend . 

Now in this case product display on product list but when we go to the product view page it show product out of stock.

**Comment by dudzio12** [comment]
https://github.com/magento/magento2/issues/22000

**Comment by maghamed** [comment]
@jorgb90 @dudzio12  the product, in fact, is gone when the order is placed. Thus, it's not possible to place another order with this product, neither to add it to a shopping cart. Even if you will visit the product page - the status of that product would be - "Out of Stock".

The reason why the product still appears on the category page and search result page is that we don't apply Reservations (created as a result of order placement) into consideration on these scenarios. So the product will disappear from these pages as soon as the order would be processed and shipment created. It's quite similar to cache invalidation. The main reason why the system behaves the way it behaves right now is a performance optimization because it's quite a costly operation to retrieve and apply reservations for a bunch of products.

**Comment by dudzio12** [comment]
@maghamed Could you answer my question?https://github.com/magento/magento2/issues/22000#issuecomment-477545146

**Comment by maghamed** [comment]
hey @dudzio12 ,

I've answered you on Magento GitHub , you can find my answer here - https://github.com/magento/magento2/issues/22000#issuecomment-478251209

**Comment by VincentMarmiesse** [comment]
Hi @maghamed,

I'm not sure to understand why this issue is closed, there *is* an issue right?
If the setting `Admin > catalog >stock option > Display Out of Stock Products` is set to No, product should disappear as soon as it gets an order (ie a reservation).

I understood it's done on purpose because it can causes some performance issues, but it's still a bug don't you think?

**Comment by dbkab** [comment]
any updates on this issue? this is really problematic in our case since the majority of our catalog consists of unique single products..

**Comment by schnere** [comment]
For anyone searching for a solution, take a look at 
`Magento\InventoryCatalog\Model\ResourceModel\AddStockDataToCollection`

I've tried to join inventory_reservation table and calculate the salable qty, which just did not work  beacuse I need the salable qty in a where clause where the variable is not available when getSize() is called on the colletion. 
For this reaseon I did a subquery in the where clause:
`(SELECT SUM(inventory_reservation.quantity) FROM inventory_reservation WHERE inventory_reservation.sku = ".Collection::MAIN_TABLE_ALIAS.".sku GROUP BY inventory_reservation.sku)`

I know this is not the best solution, but works as expected. This is just a hint for those who have the same problem, not a complete solution.

**Comment by ishakhsuvarov** [comment]
@schnere Did you see any performance impact with this solution applied?

**Comment by schnere** [comment]
> Did you see any performance impact with this solution applied?

No, but the inventory_reservation has only a couple of entries and the categories not more than 100 products. There will be an impact on installations with more orders and a greater amount of products, but it should not be a huge impact.

But, of course, it would be better to handle it within a join and find a solution for the getSize() method.
