### ISSUE TITLE
Reservations CLI

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/inventory#2140]
### Description
Admin UI for reservations was not created intentionally, as it's not intended to be viewed of manipulated by the merchant. Nevertheless, when testing advanced user scenarios involving new Inventory absence of UI for the Reservations may be frustrating and create challenge in understanding how inventory quantities are calculated and if everything is calculated correct. 

One of the main scenarios to be covered by this CLI command is calculation of SUM of reservations for the completed orders, and determine if there are any inconsistencies. Generally, Completed order should have a sum of 0.

### Expected behavior
CLI command to view inventory reservations data allows to get the list of reservations along with their sales event information, quantities, stock id projected on the relevant completed orders.

### Possible development strategy
1. Select all of the reservations, having `order` as a business type and any of the event types meaning it's completed (not `pending`, or `placed`)
2. Calculate sum of quantities for those orders
3. Display those, which have sum greater or less then zero

**Comment by lorikrell** [comment]
CLI command would be awesome! We will need to document this in the docs. Will create a doc ticket.

**Comment by maghamed** [comment]
Moved from #MSI Slack:
what we want is to add 3 CLI commands:
1. Will find all the reservations created for Completed Orders (statuses: completed, canceled, closed) where the summed up reservation quantity does not equal `0`
2. Will find Open orders (statuses: processing, pending) for which we don't have initial reservation created (the issue when merchant migrated from 2.0/2.1/2.2 with open orders and then started to use MSI which creates compensational reservation at shipment time).

These first two commands will provide Orders in the scope of which we have affected Salable Quantities of products, which need to be adjusted.

3rd command will get these Orders/SKUs and depending on the flag (+ or -) will compensate these orders with either Positive or Negative reservation. Here is important part - we would not remove existing reservations from DB, because it's irreversible process, instead we will created special type of reservation with "Manual Adjustment" business event type. Thus, potentially you can always roll them back.
That's the process to adjust Salable Quantity via Reservation CLI tools

**Comment by ishakhsuvarov** [comment]
Moved additional points to #2169 and #2170.
Closing this ticket, as the command in question was merged in #2148

**Comment by cscd98** [comment]
@ishakhsuvarov What tables do you need to empty manually to do this?

inventory_reservation ?
