### ISSUE TITLE
DOCS - CLI Command for Reservations

### ISSUE THREAD

**Issue by lorikrell** [magento/inventory#2143]
Document in the DevDocs the CLI commands for:

CLI command to view inventory reservations data allows to get the list of reservations along with their sales event information, quantities, stock id projected on the relevant completed orders.

Possible development strategy:
* Select all of the reservations, having order as a business type and any of the event types meaning it's completed (not pending, or placed)
* Calculate sum of quantities for those orders
* Display those, which have sum greater or less then zero

PRs/Issues for documentation:
- `bin/magento inventory:reservation:list-inconsistencies` : see the given inconsistencies between database reservations and orders submitted/completed/shipped/shipped/etc. (PR 2184 | Issues 2140 & 2169 | dependent on PR 2171﻿)
see improved CLI commands PR https://github.com/magento-engcom/msi/pull/2199 (most recent)

Run bin/magento inventory:reservation:list-inconsistencies to see inconsistencies
Run bin/magento inventory:reservation:list-inconsistencies -r | bin/magento inventory:reservation:create-compensations in order to pass inconsistencies to compensation command.
Run bin/magento inventory:reservation:list-inconsistencies again - no inconsistencies should be present
- `bin/magento inventory:reservation:create-compensations` :  to fix reservation inconsistencies (related to list-inconsistencies) (PR 2184﻿ | Issues 2140﻿ & 2169 | dependent on PR 2171﻿﻿)
- `bin/magento inventory:reservation:list-missing-reservation [options]` : Show all orders and products without initial reservation. (Issue 2169)
- `bin/magento inventory:reservation:complete-order-inconsistency` : see order reservation inconsistencies (PR 2148﻿ | Issue 2140)

**Comment by maghamed** [comment]
Moved from #MSI Slack:
what we want is to add 3 CLI commands:
1. Will find all the reservations created for Completed Orders (statuses: completed, canceled, closed) where the summed up reservation quantity does not equal `0`
2. Will find Open orders (statuses: processing, pending) for which we don't have initial reservation created (the issue when merchant migrated from 2.0/2.1/2.2 with open orders and then started to use MSI which creates compensational reservation at shipment time).

These first two commands will provide Orders in the scope of which we have affected Salable Quantities of products, which need to be adjusted.

3rd command will get these Orders/SKUs and depending on the flag (+ or -) will compensate these orders with either Positive or Negative reservation. Here is important part - we would not remove existing reservations from DB, because it's irreversible process, instead we will created special type of reservation with "Manual Adjustment" business event type. Thus, potentially you can always roll them back.
That's the process to adjust Salable Quantity via Reservation CLI tools

**Comment by lorikrell** [comment]
In review.

**Comment by lorikrell** [comment]
Content merged to devdocs integration branch for 1.1.2. Closing
