### ISSUE TITLE
Order Ready for Pickup tests coverage

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/inventory#2164]
### Description
Merging #2127 created a gap in the automatic tests coverage. Feature must be covered by a decent set of tests by the time of the release.

### To Do
* [ ] Integration tests created for Order Ready For Pickup feature
* [ ] Functional Tests cover the UI part of the feature

**Comment by TBlindaruk** [comment]
The same as https://github.com/magento-engcom/msi/issues/2163

**Comment by novikor** [comment]
I suggest splitting the issue into 2: first for Unit/Integration/API-functional and the second one for MFTF.

In this case, it will be merged faster.

Or I`ll implement it in different PRs related to the same issue.

**Comment by novikor** [comment]
@TBlindaruk , thank you for collaboration. I`ll close the duplicate.

**Comment by ishakhsuvarov** [comment]
@novikor Feel free to split it in any way. We are good with it as long as feature is covered with tests :)

**Comment by vpodorozh** [comment]
@novikor - when do you expect it to be finished?
I need to know to plan my time. Thx.

**Comment by novikor** [comment]
@vpodorozh  - we have not any strict deadlines at the moment.

Anyway, earlier is better.

**Comment by TBlindaruk** [comment]
@vpodorozh How your progress is?

**Comment by ishakhsuvarov** [comment]
Looks like there is no progress

**Comment by novikor** [comment]
@vpodorozh has committed to do it next week.

In Vlad we trust (no)

**Comment by vpodorozh** [comment]
> @vpodorozh has committed to do it next week.
> 
> In Vlad we trust (no)

@novikor ... check [this](https://github.com/magento-engcom/msi/commit/8378eb210490170ea169ac21f562613400a2ebe8#diff-8067531c077b8d7cb29f9f5be449a4ffR124) ...

**Comment by novikor** [comment]
@vpodorozh , should I create a PR with 1 code line of changes?)

**Comment by vpodorozh** [comment]
> @vpodorozh , should I create a PR with 1 code line of changes?)

@novikor - in fact, you will need to change at least 3 lines of code, it is not the only bug - take a look at two other test cases with comments.
But you know, nevermind - I'll fix it for you :)

**Comment by vpodorozh** [comment]
Note about MFTF tests coverage - it is not possible to do right now because "Order Ready for Pickup" functionality can be present in Admin on Order page only in case there is a row in `inventory_pickup_location_order` table with current order_id and defined pickup_location_code.
Data into `inventory_pickup_location_order` can be passed only via manual SQL query for now (functionality development is in progress), also there is no API that can insert data there.

**I'll check what is possible to do now,** I have two options:
1. Create an API for adding order->pickup_location relation;
OR
2. just prepare actionGroups for now and wait till functionality be fully implemented.

UDP: we can just use order extension attributes for saving pickup location
`\Magento\InventoryInStorePickup\Plugin\Sales\Order\SavePickupLocationForOrderPlugin::afterSave`

**Comment by vpodorozh** [comment]
Hey Hey Hey - I'm back - working on MFTF coverage

**Comment by swnsma** [comment]
Does it still relevant?

@ishakhsuvarov @vpodorozh

**Comment by ishakhsuvarov** [comment]
Seems to be merged now. Closing
