### ISSUE TITLE
product quantity issue with MSI after upgraded to Magento open source 2.3.1 from 2.2.5

### ISSUE THREAD

**Issue by rajesh-xcube** [magento/inventory#2330]
### Summary (*)

My production Magento open source version is 2.2.5 and want to upgrade to 2.3.1.
I have took the production copy(both db and file) and upgraded to 2.3.1.
If I do the shipment to pending orders then quantity getting decreased due to MSI extension.
Main cause of issue here, in Magento 2.2.x product quantity decreasing while placing order where as in 2.3.x product quantity decreasing while shipment .
### Examples (*)

I have product Iphone-X with quantity 100 in 2.2.5 instance and got the 10 orders for Iphone-X but not yet shipped.
Then I have upgrade to 2.3.1 then Iphone-X quantity 90 and saleable quantity 90.
If I do the shipment for 10 Iphone-X products then quantity become 80 and saleable quantity 90.
Here is the issue I can sale 90 but I can ship 80 products only. Here is inconsistency in product quantity and saleable quantity.
 
 
### Proposed solution

While upgrading form 2.2.x to 2.3.x, MSI extension need to make current quantity as sable quantity then increase quantity based on the pending order products(as product quantity is decreased in 2.2.x while placing order).

**Comment by ishakhsuvarov** [comment]
Hi @rajesh-xcube 

Indeed this can happen, and it used to be a sort of a known issue. It's also one of the reasons that MSI modules are not enabled by default when upgrading from 2.2.x.

The problem in this case is that [compensating reservation](https://devdocs.magento.com/guides/v2.3/inventory/reservations.html) is placed in the system when shipment and source qty deduction happens, but since it was just upgraded there is nothing to compensate. This causes qty to jump up by the amount shipped for orders placed but not shipped pre-upgrade.

There was a lot of work done on this issue in the release 1.1.2 of MSI (which is going to be bundled with upcoming 2.3.2 Magento release) and we have come up with the CLI tool which is designed to appropriately compensate incorrect reservations based on business events.

You may find reference on the introduced CLI in the [Magento DevDocs](https://devdocs.magento.com/guides/v2.3/inventory/inventory-cli-reference.html). If you wish to experiment with this release and make sure this tool is suitable for your case you may try [installing `1.1.2-beta2`](https://github.com/magento-engcom/msi/wiki/MSI-Release-Notes-and-Installation#msi-112-beta) release, which already contains this tooling. This release is expected to be compatible with Magento 2.3.1, however not officially supported.

Please let me know should you have any further questions.

Thanks!

**Comment by ishakhsuvarov** [comment]
Closing due to long inactivity. Proposed solution is still valid.
