### ISSUE TITLE
Magento 2.3.2 : Warning during di compile - Reference to undeclared plugin with name 'stockedProductsFilterPlugin'

### ISSUE THREAD

**Issue by ameshca** [magento/inventory#2590]
### Preconditions (*)

1. Magento 2.3.2(composer install)

### Steps to reproduce (*)

1. Do the di compile - bin/magento s:d:c

### Expected result (*)

1. Complete the compilation without any warnings and errors

### Actual result (*)

1. While compiling its showing the warning as "Reference to undeclared plugin with name 'stockedProductsFilterPlugin'"(the warning is being outputted in the files var/log/system.log and var/log/debug.log)

When i debugged this case and i found that in Magento 2.3.0 there was a plugin available with this name in 'module-elasticsearch' module and in Magento 2.3.2 that plugin is removed from the module. But in the module 'module-inventory-elasticsearch' we found a code to disable that plugin like below
`<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
<type name="Magento\CatalogSearch\Model\Indexer\Fulltext\Action\DataProvider">
    <plugin name="stockedProductsFilterPlugin" disabled="true"/>
    <plugin name="stockedProductFilterByInventoryStockPlugin" type="Magento\InventoryElasticsearch\Plugin\CatalogSearch\Model\Indexer\Fulltext\Action\DataProvider\StockedProductFilterByInventoryStock"/>
</type>`
but no such plugin definition is currently existing, so this shows the warning message.

**Comment by nicoaghe** [comment]
Hello @sdzhepa!
Any idea of the release date?
Thanks!

**Comment by ishakhsuvarov** [comment]
@ameshca @hostep @nicoaghe 
Issue has been identified and fixed for Magento 2.3.3 release. 

Plugin has been returned to codebase with some slight adjustments and currently neither warning nor specific issues with Elastic and Inventory do not pop up.

Unfortunately the fix is currently in one of the private branches and I am unable to share the working link to the commit, but it's definitely a part of 2.3.3.

Regarding the release dates I would suggest referring to the devdocs article on this matter: https://devdocs.magento.com/release/

**Comment by AndyJAllen** [comment]
So is the solution just to remove the di.xml reference?

**Comment by hostep** [comment]
It looks like it was fixed in 2.3.3 by re-adding the plugin in the CatalogSearch module (was previously in the Elasticsearch module in Magento 2.3.1 as mentioned by @ameshca). Commit which seems to fix it: https://github.com/magento/magento2/commit/9687ccf68d7d6c8b6059e3bc018e28ac60915962#diff-10fab71dd6e74c497265a2db0403f7ff

**Comment by ishakhsuvarov** [comment]
As correctly mentioned by @hostep it was fixed and released with 2.3.3. 

Commit is now also available in `2.3-develop` branches in most of the repositories so git installations would not be affected anymore.
