### ISSUE TITLE
The constant EARTH_RADIUS_KM needs to be public not private.

### ISSUE THREAD

**Issue by ankurvr** [magento/inventory#3112]
### Summary (*)
There is nothing private in that constant value so better making it public so it can be used in other extensions.

### Examples (*)
I would like to use it somewhere with different distance finding algorithm in my extension. Then i can't use the constant `EARTH_RADIUS_KM` because it's private.

### Proposed solution
Removing private scope of variable. So it can be accessed from anywhere.
Code: https://github.com/magento/inventory/blob/fdc539bf9bff3412e61b0ba252c3b26ad73e0b7f/InventoryDistanceBasedSourceSelection/Model/DistanceProvider/Offline/GetDistance.php#L19

**Comment by ankurvr** [comment]
@magento I am working on this

**Comment by sidolov** [comment]
Hi @ankurvr , the reason to make this constant private was to avoid coupling between objects and dependencies between different modules, also such approach makes it impossible to use inheritance for the constant and we highly recommend using composition during development instead of inheritance. If you need similar constant in your extension - please define it in your implementation as well.

I'm closing this issue since it contradicts our technical guidelines and the current design is correct.
