### ISSUE TITLE
Wrong DocBlocks

### ISSUE THREAD

**Issue by aleron75** [magento/inventory#52]
Digging in the code of the Inventory module, I've found a repetition of the following DocBlock above `__construct()` methods:

```
/**
 * SourceCarrierLinkManagement constructor
 *
 * @param ResourceConnection $connection
 */
```
I add this issue as a reminder to fix the `SourceCarrierLinkManagement` reference with the correct class name in which the constructor is declared.

**Comment by naydav** [comment]
Classes with mistake are 
`\Magento\Inventory\Model\ResourceModel\SourceItem\SaveMultiple`
`\Magento\Inventory\Model\ResourceModel\StockSourceLink\SaveMultiple`

@maghamed @aleron75 
Need to think maybe we do need to write comments like `SourceCarrierLinkManagement constructor`
because these comments do not have usefull information

**Comment by naydav** [comment]
Merged in https://github.com/magento-engcom/msi/pull/103
