### ISSUE TITLE
Add Backorder Support to MSI

### ISSUE THREAD

**Issue by vrann** [magento/inventory#601]
AC:
- adding product to shopping cart should take into account backorders index
- is salable should take into account backorders
- reservations should take into account backorders

**Comment by jonpday** [comment]
@vrann is the intention for backorder configuration to be global still (per current M2.2 functionality) or will the configuration be able to be per-stock (or per-source)? If it can't be per-stock, then is per-website possible?

**Comment by maghamed** [comment]
Hey @jonpday , sorry for the delay in response. 
But our strategy regarding most of the Inventory configuration options is to specify configuration on the level of Stock, with the ability to overwrite on the StockItem level. 

The only exception to this rule is Low Stock notifications because Low Stock is supposed to be specified per Sources (warehouses).

All other options are applied to Stock (aggregates).
This is true for Backorder as well. Backorders could be specified on the level of Stock and overwrite on StockItem level
