### ISSUE TITLE
Investigate applying of feature "Allow Multiple Boxes for Shipping" from Advanced Inventory on product page

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#778]
Investigate applying of feature "Allow Multiple Boxes for Shipping" from Advanced Inventory on product page

**Comment by p-bystritsky** [comment]
Seems like this option is used to allow carriers, such as DHL, to split order into several separate packages based on package maximum weight.

**Comment by sidolov** [comment]
@smoskaluk I agree with @p-bystritsky , this option can be used by shipping carriers in case when the product can be sold with decimal qty and carrier has an ability to split an order to few packages if it's weight > max shipping weight (defined by carrier). It shouldn't have any impact on the inventory logic. 
I'm closing the issue since there is nothing to do with it.
