### ISSUE TITLE
Downloadable and Virtual products remain In Stock after all quantity is bought.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/inventory#822]
### Steps to reproduce

1. Create Downloadable and Virtual products.
2. Buy all quantity of Downloadable and Virtual products.
3. Complete Order.

### Expected result

1. Downloadable and Virtual products are Out Of Stock.

### Actual result

1. Downloadable and Virtual products are In Stock.

**Comment by giuseppemorelli** [comment]
I try to fix this problem (MageTitans IT 2018 Contribution Day)

**Comment by giuseppemorelli** [comment]
@maghamed @naydav 

So this is the point: 
- for virtual and downloadable we don't have ship section
- no ship section = no place to decrease "real" quantity, but if you try to add the product (which should be out of stock) you have an error because `inventory_reservation` was fill up correctly

![image](https://user-images.githubusercontent.com/1280769/38365707-ab41cbe2-38dd-11e8-945c-f0eef697eb4e.png)

![image](https://user-images.githubusercontent.com/1280769/38365719-b19139ba-38dd-11e8-9e98-9692699db673.png)

![image](https://user-images.githubusercontent.com/1280769/38365725-b73214f2-38dd-11e8-9573-104ef8b783ec.png)

I think that this issue is a "feature task" because we don't have a bug, but a missing feature to implement.
It's necessary to decide when and where we want to decrease reservation quantity for virtual and downloadable products -> maybe on invoice section only for these kind of products?

**Comment by vadimjustus** [comment]
Related PR https://github.com/magento-engcom/msi/pull/788

**Comment by giuseppemorelli** [comment]
@maghamed  There is a branch created on msi repository: 822
It was created from 430-Source_Deduction branch.

What is inside the code:
- decrease qty after invoice save only for virtual and downloadable products
- used the event `sales_order_invoice_save_after`
- I assume that virtual/downloadable products are only available on default source, if not we need to implement the same GUI as we have for shipment

Ps. I found an error if I create a shipment (in any cases) but I think there is some work in progress in the 430-branch.
