### ISSUE TITLE
Wrong salable qty of simple product after placing order with it

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#825]
### Preconditions

1. Magento MSI
2. New stock with new source created
3. Simple product "sku1" created with Qty = 10 on default source  

### Steps to reproduce

1. Place order with "sku1" qty =10
2. Open "sku1" product page in admin -> Product Salable Quantity tab

### Expected result

1. Product Salable Quantity should be 0 in admin

### Actual result

1. Product Salable Quantity = -10 in admin

**Comment by RomaKis** [comment]
Can not reproduce on latest 2.3-develop.

**Comment by Enterframe99** [comment]
We are in 2.3.
When we submit an order we have the result described by smoskaluk but this is true for the first 20/30 seconds; after that time the saleable quantity return to the correct value.
We think that is due to catalog reindex time, but if a customer make an order in this few seconds we can receive an order for a product that isn't avaiable.
