### ISSUE TITLE
Need to remove all cross checks between Inventory in catalog regarding verification that SKUs being operated in Inventory exist in Catalog 

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#889]
Need to remove all cross checks between Inventory in catalog regarding verification that SKUs being operated in Inventory exist in Catalog.

For example, currently, we have the similar check at the time of Inventory Import. 
Where there is a query to Catalog Product to make sure that all the Source Items have match Product SKU in Catalog.

This kind of validation should be removed and MSI should allow to have SKUs not referring to Catalog

**Comment by naydav** [comment]
In scope of this task need to fix \Magento\CatalogImportExport\Model\Import\ProductTest::testImportWithDifferentSkuCase

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1019

**Comment by Djohn12** [comment]
Hi there,

On magento 2.4.6-p3 instance I am still hitting a error `{"message":"Could not save Source Item"}` when sending POST request to endpoint `rest/V1/inventory/source-items`, passing any sku not existent in `catalog_product_entity` table.

I might be wrong but in my humble opinion there might still be a check between Inventory and Catalog on the API updates.

However, I also found an 'opposite' issue where it's asked to add a check for sku existence when importing stock_source : https://github.com/magento/inventory/issues/270

Not sure what's the expected behavior nowadays, anyone care to explain what is the expected behavior ? Check sku or not ? Same behavior expected on admin stock_source import && API Post on source-item endpoint update ?

Thanks in advance
